CREATE TABLE IF NOT EXISTS documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ext_id INTEGER NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT 0,
    file_path TEXT NOT NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
)
